version: '3'

services:
  # postgres:
  #   image: postgres:13.3-alpine
  #   ports:
  #     - "5444:5432"
  #   environment:
  #     POSTGRES_DB: pix_lcms
  #     POSTGRES_HOST_AUTH_METHOD: trust

  # redis:
  #   image: redis:5.0.7-alpine
  #   ports:
  #     - "6380:6379"

  brix-editor:
    image: node:14.17.6
    build: 
      dockerfile: ./Dockerfile
    volumes:
        - ./:/var/www
    ports:
      - "4300:3000"
