FROM node:14.17.6 as dev

USER root
WORKDIR /code
COPY . .

EXPOSE 3000
WORKDIR /code/api
RUN npm cache verify
RUN npm install -g npm@6.14.15
RUN npm install


COPY --chown=node:node . /code 

RUN npm ci

CMD [ "npm", "run", "start" ]

# USER root
# WORKDIR /code
# COPY . .

# WORKDIR /code/api

# RUN npm cache verify
# RUN npm install -g npm@6.14.15
# RUN npm ci

# CMD [ "npm", "run", "start" ]

