version: '2.22'

services:
  # postgres:
  #   image: postgres:13.3-alpine
  #   ports:
  #     - "5444:5432"
  #   environment:
  #     POSTGRES_DB: pix_lcms
  #     POSTGRES_HOST_AUTH_METHOD: trust

  # redis:
  #   image: redis:5.0.7-alpine
  #   ports:
  #     - "6380:6379"

  brix-editor:
    image: pix/editor
    build: 
      dockerfile: ./Dockerfile
    volumes:
      - ./:/code
      - ./docker-ember-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4300:80"

  brix-editor-api:
    image: pix/editor-api
    hostname: localhost
    build: 
      dockerfile: ./Dockerfile.api
    volumes:
      - ./:/code
    ports:
      - "3002:3000"

